module.exports = {
    rules: {
        "constructor-super": "error",
        "getter-return": ["error", {
            allowImplicit: true,
        }],
        "no-async-promise-executor": "error",
        "no-class-assign": "error",
        "no-compare-neg-zero": "error",
        "no-cond-assign": "error",
        "no-const-assign": "error",
        "no-constant-binary-expression": "error",
        "no-constant-condition": "error",
        "no-constructor-return": "error",
        "no-debugger": "warn",
        "no-dupe-args": "error",
        "no-dupe-class-members": "error",
        "no-dupe-else-if": "error",
        "no-dupe-keys": "error",
        "no-duplicate-case": "error",
        "no-duplicate-imports": "off",
        "no-empty-character-class": "error",
        "no-empty-pattern": "error",
        "no-ex-assign": "error",
        "no-fallthrough": ["error", {
            allowEmptyCase: true,
        }],
        "no-func-assign": "error",
        "no-import-assign": "error",
        "no-inner-declarations": "error",
        "no-invalid-regexp": "error",
        "no-irregular-whitespace": "error",
        "no-loss-of-precision": "error",
        "no-new-symbol": "error",
        "no-obj-calls": "error",
        "no-prototype-builtins": "error",
        "no-self-assign": "error",
        "no-self-compare": "error",
        "no-setter-return": "error",
        "no-sparse-arrays": "error",
        "no-this-before-super": "error",
        "no-undef": "error",
        "no-unexpected-multiline": "error",
        "no-unreachable": "warn",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": "error",
        "no-unsafe-optional-chaining": "error",
        "no-unused-private-class-members": "warn",
        "no-unused-vars": ["error", {
            args: "after-used",
            ignoreRestSiblings: true,
            argsIgnorePattern: "^_",
            destructuredArrayIgnorePattern: "^_",
            caughtErrors: "all",
            caughtErrorsIgnorePattern: "^_",
        }],
        "use-isnan": "error",
        "valid-typeof": "error",
        "capitalized-comments": ["off"],
        "curly": ["error", "all"],
        "default-param-last": ["error"],
        "eqeqeq": ["error", "always", {
            null: "ignore",
        }],
        "func-names": ["error", "always"],
        "grouped-accessor-pairs": ["error", "anyOrder"],
        "max-nested-callbacks": ["error", {
            max: 10,
        }],
        "no-alert": "error",
        "no-caller": "error",
        "no-console": "off",
        "no-empty": "warn",
        "no-empty-function": "warn",
        "no-eval": "error",
        "no-extra-boolean-cast": ["error", {
            enforceForLogicalOperands: true,
        }],
        "no-extra-semi": "error",
        "no-global-assign": "error",
        "no-implicit-coercion": ["error", {
            allow: ["!!"],
        }],
        "no-implied-eval": "error",
        "no-labels": "error",
        "no-new": "error",
        "no-new-func": "error",
        "no-nonoctal-decimal-escape": "error",
        "no-octal": "error",
        "no-proto": "error",
        "no-return-assign": ["error", "always"],
        "no-shadow-restricted-names": "error",
        "no-useless-escape": "error",
        "no-var": "error",
        "no-with": "error",
        "prefer-const": "error",
        "prefer-object-has-own": "error",
        "prefer-promise-reject-errors": "error",
        "prefer-rest-params": "error",
        "prefer-template": "error",
        "require-await": "error",
        "require-yield": "error",
        "no-multi-str": "error",
        "spaced-comment": ["error", "always", {
            line: {
                exceptions: ["-+"],
            },
            block: {
                exceptions: ["*"],
            },
        }],
        "symbol-description": "error",
        "arrow-parens": "error",
        "arrow-spacing": ["error", {
            "before": true,
            "after": true,
        }],
        "brace-style": "error",
        "comma-dangle": ["error", "always-multiline"],
        "comma-spacing": "error",
        "comma-style": "error",
        "computed-property-spacing": "error",
        "dot-location": ["error", "property"],
        "eol-last": "error",
        "func-call-spacing": "error",
        "function-call-argument-newline": ["error", "consistent"],
        "indent": ["error", 4, {
            SwitchCase: 1,
            offsetTernaryExpressions: true,
        }],
        "jsx-quotes": "error",
        "key-spacing": "error",
        "keyword-spacing": "error",
        "line-comment-position": "error",
        "linebreak-style": ["error", "unix"],
        "lines-around-comment": ["off"],
        "lines-between-class-members": "off",
        "max-len": ["error", 180],
        "max-statements-per-line": ["error", {
            max: 1,
        }],
        "new-parens": "error",
        "newline-per-chained-call": ["error", {
            ignoreChainWithDepth: 3,
        }],
        "no-mixed-spaces-and-tabs": "error",
        "no-multi-spaces": "error",
        "no-multiple-empty-lines": ["error", {
            max: 2,
        }],
        "no-tabs": "error",
        "no-whitespace-before-property": "error",
        "quotes": "error",
        "rest-spread-spacing": ["error", "never"],
        "semi": "error",
        "semi-style": ["error", "last"],
        "space-before-blocks": "error",
        "space-before-function-paren": ["off"],
        "space-in-parens": "error",
        "no-trailing-spaces": "error",
        "object-curly-newline": ["error", {
            ObjectExpression: {
                minProperties: 12,
                multiline: true,
                consistent: true,
            },
            ObjectPattern: {
                minProperties: 12,
                multiline: true,
                consistent: true,
            },
            ImportDeclaration: {
                minProperties: 100,
                multiline: true,
                consistent: true,
            },
            ExportDeclaration: {
                minProperties: 5,
                multiline: true,
                consistent: true,
            },
        }],
        "object-property-newline": ["off"],
        "object-curly-spacing": ["error", "always"],
        "operator-linebreak": ["error", "before"],
    },
};
